mysite/calendar_app/urls.py
from django.urls import path

from . import views

app_name = 'calendar_app'
urlpatterns = [
    path('', views.index, name='index'),#login
    path('logout/', views.logoutUser, name='logoutUser'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('createEvent/', views.createEvent, name='createEvent'),
    path('updateEvent/<int:pk>', views.updateEvent, name='updateEvent'),
    path('deleteEvent/<int:pk>', views.deleteEvent, name='deleteEvent'),
    path('home/', views.home, name='home'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calendar_app.urls')),
]

mysite/calendar_app/models.py
from django.db import models


class Event(models.Model):
    title = models.CharField(max_length=200)
    start_date = models.DateTimeField("Czas początkowy")
    end_date = models.DateTimeField("Czas zakończenia")
    description = models.CharField(max_length=400, blank=True, default='')

    def __str__(self):
        return self.title


class RouteEvent(Event):
    start_location = models.CharField(max_length=40)
    end_location = models.CharField(max_length=40)

mysite/calendar_app/forms.py
from django.forms import ModelForm
from .models import Event


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = '__all__'

mysite/calendar_app/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *
from .models import Event


def index(request):
    template_name = 'calendar_app/index.html'
    if request.user.is_authenticated:
        return redirect('/home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/home')
            else:
                messages.info(request, "złe dane logowania")
    return render(request, template_name)


def logoutUser(request):
    logout(request)
    return redirect('/')


class DetailView(generic.DetailView):
    template_name = 'calendar_app/detail.html'
    model = Event


@login_required(login_url='/')
def home(request):
    template_name = 'calendar_app/home.html'
    event_list = Event.objects.all()
    context = {'event_list': event_list}
    return render(request, template_name, context)


@login_required(login_url='/')
def createEvent(request):
    form = EventForm()
    template_name = 'calendar_app/createEvent.html'
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/home')

    context = {'form': form}
    return render(request, template_name, context)


@login_required(login_url='/')
def updateEvent(request, pk):
    event = Event.objects.get(id=pk)
    form = EventForm(instance=event)
    template_name = 'calendar_app/updateEvent.html'

    if request.method == 'POST':
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            form.save()
            return redirect('/home')

    context = {'form': form}
    return render(request, template_name, context)


@login_required(login_url='/')
def deleteEvent(request, pk):
    event = Event.objects.get(id=pk)
    template_name = 'calendar_app/deleteEvent.html'
    context = {'event': event}

    if request.method == 'POST':
        event.delete()
        return redirect('/home')

    return render(request, template_name, context)

mysite/calendar_app/templates/calendar_app/createEvent.html
{% extends 'calendar_app/main.html' %}
    {% block context %}

        <form action="" method="POST">
        {% csrf_token %}
            <p>Tytuł</p><br>
            {{form.title}}<br>
            <p>Początkowa data:</p><br>
            <input type="datetime-local" value={{form.start_date}}<br>
            <p>Końcowa data:</p><br>
            <input type="datetime-local" value={{form.end_date}}<br>
            <p>Opis:</p><br>
            {{form.description}}<br>
            <input type="submit" value="Dodaj">
        </form>

    {% endblock %}

mysite/calendar_app/templates/calendar_app/deleteEvent.html
{% extends 'calendar_app/main.html' %}
    {% block context %}
        <p>Czy na pewno chcesz usunąć "{{event}}"</p>
        <p>Tego zdarzenia nie będzie można przywrócić</p>
        <form action="{% url 'calendar_app:deleteEvent' event.id %}" method="POST">
            {% csrf_token %}
            <a href="{% url 'calendar_app:home'%}">Cofnij</a>
            <input type="submit" value="Usuń">
        </form>
    {% endblock %}

mysite/calendar_app/templates/calendar_app/detail.html
{% extends 'calendar_app/main.html' %}
    {% block context %}

        <label>startDate</label><br><br>
        <label>{{ event.start_date }}</label><br>
        <label>endDate</label><br><br>
        <label>{{ event.end_date }}</label><br>
        <label>description</label><br><br>
        <label>{{ event.description }}</label><br>

    {% endblock %}

mysite/calendar_app/templates/calendar_app/home.html
{% extends 'calendar_app/main.html' %}
    {% block context %}

        <h1>event</h1>
        <table>
            <tr>
                <th>Tytuł</th>
                <th>Usuń</th>
                <th>Zmień</th>
            </tr>
            {% for event in event_list%}
            <tr>
                <td> <a href="{% url 'calendar_app:detail' event.id %}"> {{ event.title }}</a></td>
                <td> <a href="{% url 'calendar_app:deleteEvent' event.id %}"> usuń </a></td>
                <td> <a href="{% url 'calendar_app:updateEvent' event.id %}"> zmień </a></td>

            </tr>
            {% endfor %}
        </table>

    {% endblock %}

mysite/calendar_app/templates/calendar_app/index.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'calendar_app/css/index.css' %}">
</head>

<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				{% for message in messages %}
						<p id="messages">{{message}}</p>
				{% endfor %}
			</div>
		</div>
	</div>
</body>

</html>

mysite/calendar_app/templates/calendar_app/main.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Kalendarz</title>
</head>
<body>
    {% include 'calendar_app/navbar.html' %}

    {% block context %}

    {% endblock %}
</body>
</html>

mysite/calendar_app/templates/calendar_app/navbar.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'calendar_app/css/navbar.css' %}">
    <div class="navbar">
        <h1 >Navbar</h1>
        <a href="{% url 'calendar_app:createEvent' %}">Stwórz Event</a>
        <a href="{% url 'calendar_app:logoutUser' %}">Wyloguj</a>

    </div>
<hr>

mysite/calendar_app/templates/calendar_app/updateEvent.html
{% extends 'calendar_app/main.html' %}
    {% block context %}

        <form action="" method="POST">
        {% csrf_token %}
            {{form}}
            <input type="submit" value="Zmień">
        </form>

    {% endblock %}